### ISSUE TITLE
I own a Mac, how can I help?

### ISSUE THREAD

**Issue by Hedronmx** [ferdinandschober/lan-mouse#35]
Hey! I was wondering if I could help you out with the mac development in any way? Maybe even renting you a virtual mac?

let me know

**Comment by ferdinandschober** [comment]
Hey,
first of all: Thank you for your interest!

Are you asking about contributing, or helping in another way?

My plan is to eventually try to setup an OSX-KVM vm (I've played around with that before) and then maybe have some friends with a macbook test it on real hardware.
It will take a while though as my priority is currently to first finish the libei backend for Gnome support, implement input capture on windows and distribute everything on flatpak.

If you  (or someone you know) want to give it a go, you can always open up a PR.

The event producer and consumer api is currently a little unstable because I'm still in the process of integrating everything with async rust but any function that either takes an event to emulate or produces input events would be very helpful. Eventually it will likely be a [Stream](https://rust-lang.github.io/async-book/05_streams/01_chapter.html) of futures for input capture and an async function that takes an event to emulate for event consuming.

I will also add a Contributing.md eventually (and once the internal APIs are a little bit more stable).

**Comment by Hedronmx** [comment]
Unfortunately this project is out scope. I have no clue how to contribute as I am a web developer. I was referring to either giving you access to a mac or setting you up for a virtual mac

**Comment by ferdinandschober** [comment]
I will add that I have access to a Mac now, at least for testing purposes about once a week. I'm closing this issue in favor of #36

**Comment by feschber** [comment]
Frontend is up ;) #42
